# This is a basic workflow to make a comment on the Jira issue with the link to the build triggered by  Github Actions 
name: Code Coverage

on:
  # Triggers the workflow on pull request events to the mater branch
  pull_request:
    branches: [ master ]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions-ecosystem/action-regex-match
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.head_ref }}
          regex: 'WUG-[0-9]+'

      - name: Test Step
        env:
          REGEX_MATCH: ${{ steps.regex-match.outputs.match }}
          JIRA_WEBHOOK_URL_WITH_ISSUE: '${{ secrets.JIRA_WEBHOOK_URL }}?issue=${{steps.regex-match.outputs.match}}'
          GITHUB_WORKFLOW_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          REQUEST_PAYLOAD: '{"data": {"build_url": "$GITHUB_WORKFLOW_URL"}}'
        run: |
              echo $GITHUB_WORKFLOW_URL
              echo $JIRA_WEBHOOK_URL_WITH_ISSUE
              echo $GITHUB_REPOSITORY
              echo $GITHUB_RUN_ID
              echo $REQUEST_PAYLOAD

      # https://github.com/marketplace/actions/webhook-post-action
      #- uses: muinmomin/webhook-action@v1.0.0
      #  env: 
      #    REGEX_MATCH: ${{ steps.regex-match.outputs.match }}
      #    JIRA_WEBHOOK_URL_WITH_ISSUE: '${{ secrets.JIRA_WEBHOOK_URL }}?issue=${{steps.regex-match.outputs.match}}'
      #    GITHUB_WORKFLOW_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' 
      #  if: ${{ steps.regex-match.outputs.match != '' }}
      #  with:
      #    url: "$JIRA_WEBHOOK_URL_WITH_ISSUE"
      #    data: '{"data": {"build_url": "$GITHUB_WORKFLOW_URL"}}'

      - name: Send Post Request on Jira
        uses: fjogeleit/http-request-action@master
        env: 
          GITHUB_WORKFLOW_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          contentType: 'application/json'
          url: '${{ secrets.JIRA_WEBHOOK_URL }}'
          method: 'POST'
          data: '{"issues":["${{ steps.regex-match.outputs.match }}"], "data": {"build_url": "${{ GITHUB_WORKFLOW_URL }}"}}'


#  --data '{"issues":["WUG-35456"], "data": {"releaseVersion":"AHHHH"}}'